CheckerNetwork/spark-checker

- .github/workflows/ci.yml
Release notes:
https://github.com/filecoin-station/zinnia/releases/tag/v0.13.0
> chore: upgrade Zinnia to v0.13.0

- .github/workflows/ci.yml
Release notes:
https://github.com/filecoin-station/zinnia/releases/tag/v0.14.0
> chore: upgrade Zinnia to v0.14.0

- lib/spark.js
- test/integration.js
- test/spark.js
1. fix tests to use the new `GET /measurements/:id` API
2. submit retrieval results via `POST /measurements` API
3. choose retrievals using `GET /rounds/current`
See https://github.com/filecoin-station/spark/issues/13
> feat: retrieval tasks based on IE rounds

- lib/spark.js
- test/spark.js
Rename the measurement field to match the changes we are making on the spark-api and spark-evaluate sides.
The tests will keep failing until we deploy https://github.com/filecoin-station/spark-api/pull/97
> feat: rename walletAddress to participantAddress

- lib/activity-state.js
- lib/spark.js
- test/spark.js
Ref https://github.com/filecoin-station/spark/pull/28#discussion_r1343896336
@bajtos I've removed `.success`, since the presence of `.carChecksum` marks a successful retrieval
> Change success definition

- lib/activity-state.js
- lib/constants.js
- lib/deno-encoding-hex.js
- lib/spark.js
- test/spark.js
The first commit introduces a limit of 200 MB on the amount of data we are willing to download. See https://github.com/filecoin-station/spark/issues/16
The second commit computes SHA-256 hash of the downloaded content and submits it in measurements. See https://github.com/filecoin-station/spark/issues/30
The measurements data submitted to SPARK API has two new fields:
- `carTooLarge` indicating whether we downloaded all content or aborted in the middle
- `carChecksum` containing a [multihash](https://multiformats.io/multihash/#sha2-256---256-bits-aka-sha256) of the content
> feat: limit max download size + calculate SHA-256 checksum

- lib/spark.js
Report the healthy state as soon as we can fetch round details from spark-api. This way Station Desktop becomes "online" faster on startup or after network disconnect.
> fix: report healthy state earlier

- lib/spark.js
- test/spark.js
SPARK is about retrieval testing not load testing.
Currently, more than 90% of retrievals fail on timeout or server errors. There is little value in checking whether we can download the entire CAR file; it's more important to know whether SPs are advertising FIL+ deals to IPNI and accepting HTTP-based retrieval requests.
SPARK is also currently unable to fetch and verify CAR files larger than 200MB, which further reduces the value of fetching full CAR files.
Let's fetch the root block for the time being.
- This should significantly reduce the load on "good" SPs.
- It provides enough data to help "bad" SPs fix their setup.
/cc @rvagg @hannahhoward @willscott @gruns do you have any thoughts on this?
See also:
- https://github.com/filecoin-station/roadmap/issues/52
> feat: fetch only the root block

- lib/constants.js
- lib/spark.js
Links:
- https://github.com/filecoin-station/spark-api/pull/172
- https://github.com/filecoin-station/roadmap/issues/52
> feat: honour `maxTasksPerRound` from spark-api

- .github/workflows/publish.yml
This automatically publishes the module source ip IPFS/IPNI, when a release has been created. Then, Station Core's auto updater will be able fetch it.
All secrets have been configured on the repo, and stored in 1password with additional context.
Caveat: If we create a new stable release, which is however not the "latest" version, the action will publish it and overwrite the current IPNI pointer anyways. I see this as low risk atm. Do you have any ideas how we could circumvent that?
> ci: add publish

- test/integration.js
Enable assertion that was commented out until we improve spark-api.
> test: measurement.indexResult

- lib/spark.js
When the storage provider does not advertise HTTP retrieval, but advertises Grapsync retrievals, then let's perform the retrieval check.
This was my original intention when I implemented IPNI querying.
I discovered the problem by accident while working on #55. Unfortunately, there is no easy way how to write a reliable automated test for this, as we would need a CID that's guaranteed to have only Graphsync advertised to IPNI.
FWIW, we want to move to testing HTTP retrievals only and drop support for Graphsync (see https://github.com/filecoin-station/spark/issues/46). However, since we are not there yet, I feel this bug is still worth fixing.
Here is a script I used to verify the fix manually. Please not you need to include changes from #55 to be able to reproduce the problem.
```js
import …
```
> fix: check Graphsync retrievals too

- .github/workflows/ci.yml
- lib/spark.js
- test/spark.js
- Get station_id from Zinnia env and add to measurements submission
- Bump Zinnia version for GH workflow
This PR supersedes and closes #59. GitHub did not run CI checks there.
Links:
- https://github.com/filecoin-station/roadmap/issues/96
> Feat: Get station_id from Zinnia env and add to measurements submission 

- .github/workflows/ci.yml
Release notes:
https://github.com/filecoin-station/zinnia/releases/tag/v0.18.2
> ci: upgrade Zinnia to v0.18.2

- .github/workflows/ci.yml
https://github.com/filecoin-station/zinnia/releases/tag/v0.19.0
> ci: upgrade Zinnia to v0.19.0

- lib/spark.js
- test/spark.js
This is a temporary workaround until we figure out how to build the fixed zinnia version (see https://github.com/filecoin-station/zinnia/pull/538)
This should fix the CI builds and allow us to publish new versions from this repo.
> fix: handle legacy dev wallet provided by zinnia

- .github/workflows/ci.yml
- actions/checkout@v4
- actions/setup-node@v4
> ci: upgrade deprecated GH actions to v4

- lib/constants.js
- lib/miner-info.js
Would be nice to afterwards find out whether this is how `Request` works, or maybe a Zinnia bug.
> fix glif token not being sent

- lib/constants.js
- lib/miner-info.js
Follow up for https://github.com/filecoin-station/spark/pull/69#pullrequestreview-2058141026
> refactor rpc config

- lib/ipni-client.js
- manual-check.js
- test/integration.js
Links:
- https://github.com/filecoin-station/roadmap/issues/107
> feat: manual check for a given task

- lib/ipni-client.js
- lib/miner-info.js
- lib/spark.js
- manual-check.js
Example output before my change:
```
Retrieval failed with status code 502: no candidates found
{
timeout: false,
startAt: 2024-05-31T07:30:43.389Z,
// etc.
protocol: "graphsync",
providerAddress: "/ip4/118.212.68.22/tcp/24501/p2p/12D3KooWJJEL214g7yMFMFaE6aPRaQTLVVCNFjWeiBLUCTzP98tp"
}
Submitting measurement...
{
sparkVersion: "1.11.4",
zinniaVersion: "0.19.1",
cid: "bafykbzacechhbxnsn5dw6lx7phcfvkjc6kqsuuwl4bnynexewb5y3vtcw2fvw",
minerId: "f02894875",
timeout: false,
startAt: 2024-05-31T07:30:43.389Z,
// etc.
providerAddress: "/ip4/118.212.68.22/tcp/24501/p2p/12D3KooWJJEL214g7yMFMFaE6aPRaQTLVVCNFjWeiBLUCTzP98tp",
participantAddress: "0x000000000000000000000000000000000000dEaD",
stationId: "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
}
``` …
> fix: improve logs

- deps.ts
- lib/multiaddr.js
- lib/spark.js
- test.js
- test/multiaddr.test.js
- test/spark.js
- vendor/deno-deps.js
When we're retrieving the content using the Trustless HTTP Gateway protocol ("http"), fetch the content directly from the provider, do not use Lassie.
This should give us better visibility into various error statuses returned by providers. For example, Lassie converts the error `429 Too Many Requests` to a generic error `502 Bad Gateway`.
List of synthetic status codes corresponding to different errors we may encounter along the new codepath:
- 600 - unknown error (fallback)
- 701 - provider's multiaddr has unsupported hostname type (e.g. `ipv4` instead of `ip4`)
- 702 - provider's multiaddr is not "tcp"
- 703 - provider's multiaddr is not "https"
- 704 - provider's multiaddr has too many parts
- 801 - provider's hostname cannot be resolved via DNS
- 802 - TCP connection error
- 901 - CID …
> feat: fetch HTTP retrievals directly

- release.sh
Fail when the next version is specified as a non-semver string, e.g. "minor" or "patch".
> fix: reject non-semver strings in release.sh

- deps.ts
- lib/drand-client.js
- lib/http-assertions.js
- lib/spark.js
- lib/tasker.js
- test/drand-client.test.js
- test/spark.js
- test/tasker.test.js
- vendor/deno-deps.js
Rework the current random task selection algorithm to a deterministic algorithm using DRAND randomness and distance between the hash of the task and the hash of the node to sort the tasks in a deterministic way that's unique to each round and each node.
Design doc:
- https://www.notion.so/spacemeridian/Spark-Tasking-v3-745b0e1020bb4000ac77acafee09e683
Proof of Concept:
- https://github.com/filecoin-station/spark-evaluate/pull/287
Links:
- https://github.com/filecoin-station/spark/issues/38
- https://github.com/filecoin-station/spark/issues/27
> feat: deterministic tasking

- lib/spark.js
Exclude miner-info RPC API call and IPNI lookup from the timing information.
I realised this is a quickest & easiest way how to fix the TTFB values we are
already recording & visualising in Grafana.
Previous discussion that I decided to ignore:
- https://github.com/filecoin-station/spark/issues/54
> fix: record `startAt` just before the retrieval

- deps.ts
- lib/miner-info.js
- test/miner-info.test.js
- vendor/deno-deps.js
- **deps: add `retry` from Deno stdlib**
- **fix: retry `Filecoin.StateMinerInfo` requests**
I noticed that sometimes my Station Desktop will go offline. The module logs contain the following messages:
```
[2024-09-23T12:43:03Z INFO  module:spark/main] Calling Filecoin JSON-RPC to get PeerId of miner f02085652
{"type":"activity:error","module":"spark/main","message":"SPARK failed reporting retrieval"}
[2024-09-23T12:43:04Z ERROR module:spark/main] Error: Cannot obtain miner info for f02085652: error sending request for url (https://api.node.glif.io/): connection closed before message completed
at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
at async fetch (ext:deno_fetch/26_fetch.js:504:7)
at async rpc (file:///Users/bajtos/Library/Caches/app.filstation.desktop/sources/spark/lib/min …
```
>  fix: retry `Filecoin.StateMinerInfo` requests

- lib/spark.js
- test/spark.js
Ensure the checker prints some message at least once per minute, to prevent Station Core for considering it as stuck.
As a side effect, this also fixes the problem when maxTasksPerRound is zero, the delay is calculated as Infinity and we call `setTimeout(Infinity)`. Such call is a no-op in Deno, which causes the checker to loop very quickly and pollute the logs with too many "Completed all tasks for the current round." messages.
After this change, the message is print once per minute.
Links:
- https://github.com/filecoin-station/spark-api/pull/437
- https://github.com/filecoin-station/spark-api/pull/440
> fix: limit the delay between tasks to 60s

- test/spark.js
For #110 
Unbreak the test suite by disabling the failing test.
@bajtos what do you advise here? Shall we find another provider (if so, how? The top SP from the RSR list?), or keep this test disabled?
> Disable failing graphsync test. #110

- lib/spark.js
- test/integration.js
- test/spark.js
For #104
Next: Integrate into spark-api. This is not blocking, as submitting the measurements also already works _with_ the new property -> https://github.com/CheckerNetwork/spark-api/pull/521
> Add HEAD request. #104

- lib/multiaddr.js
- lib/spark.js
- test/multiaddr.test.js
- test/spark.js
**CHANGELOG**
1. Add support for `http-path` multi addresses in `multiaddrToHttpUrl`
2. Unit tests for `http-path` links
3. Integration tests for the error code induced by invalid `http-path` links
[Implementation Plan](https://github.com/CheckerNetwork/piece-indexer/issues/117#issuecomment-2672660743)
Subtask of:
https://github.com/CheckerNetwork/roadmap/issues/239
Related Issue:
https://github.com/CheckerNetwork/piece-indexer/issues/117
> feat: support of `http-path` multiaddresses

- lib/constants.js
- lib/spark.js
- test/spark.js
Introduce random jitter in the delay between subsequent tasks (retrieval checks).
The goal is to better spread out the requests from the network in the time, to avoid too many nodes hitting services like cid.contact at the same time.
Links:
- https://github.com/CheckerNetwork/spark-checker/issues/119
(I'll close the issue after I publish a new version of the spark checker.)
> feat: add jitter to delay between tasks

- lib/constants.js
- lib/spark.js
- package-lock.json
- test/spark.js
This PR adds a client-side max request duration timeout to prevent retrievals from lingering beyond a reasonable threshold, resolving issue #99.
- Adds `maxTimeout` tracking in `fetchCAR`
- Sets hard timeout (e.g. 90s) in addition to progress timeout (60s)
- Adds a test to ensure max timeout aborts stalled connections
> feat: add client-side max request duration timeout to Spark (#99)

- .github/workflows/dependabot-auto-approve-always.yml
- .github/workflows/dependabot-auto-approve-minor.yml
- .github/workflows/dependabot-auto-merge.yml
- .prettierrc.yaml
- lib/activity-state.js
- lib/constants.js
- lib/drand-client.js
- lib/ipni-client.js
- lib/miner-info.js
- lib/multiaddr.js
- lib/spark.js
- lib/tasker.js
- manual-check.js
- package-lock.json
- package.json
- test/drand-client.test.js
- test/http-assertions.test.js
- test/integration.js
- test/miner-info.test.js
- test/multiaddr.test.js
- test/spark.js
- test/tasker.test.js
- **chore: adopt `@checkernetwork/prettier-config`**
- **ci: setup dependabot auto-approve & auto-merge**
- **chore: `npm run lint:fix`**
Parent issue:
- https://github.com/CheckerNetwork/roadmap/issues/166
> chore: adopt `@checkernetwork/prettier-config`
